# Generated by Django 5.2.8 on 2026-02-24 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.IntegerField()),
                ('respuestas_detalle', models.JSONField(blank=True, null=True)),
                ('fecha_prueba', models.DateTimeField(auto_now_add=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='evaluacion.postulante')),
            ],
        ),
    ]
