# Generated by Django 5.2.8 on 2026-02-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='contrasena',
            field=models.CharField(default='', max_length=128),
        ),
    ]
